

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-sql-deployment
spec:
  selector:
    matchLabels:
      app: pokemon-sql
  replicas: 1
  template:
    metadata:
      labels:
        app: pokemon-sql
    spec:
      containers:
      - name: pokemon-sql
        image: oliverdj/pokemon-chart-sql:version1.0
        ports:
        - containerPort: 1433
        env:
        - name: MASTER_USER
          value: SA
        - name: SA_PASSWORD
          value: pass123?
        - name: DB_NAME
          value: PokemonDB
        - name: ACCEPT_EULA
          value: "Y"

      - name: pokemon-api
        image: oliverdj/pokemon-chart-api:version1.0
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__PokemonDatabase
          value: Server=localhost, 1433; Database=PokemonDB; User ID=SA; Password=pass123?